[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."approve-order-background"]
  included_files = ["netlify/functions/lib/fonts/**", "netlify/functions/lib/washes/**"]
